// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/game/new": {
    params: {};
  };
  "/game/:id": {
    params: {
      "id": string;
    };
  };
  "/library": {
    params: {};
  };
  "/library/:id": {
    params: {
      "id": string;
    };
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
  "/admin": {
    params: {};
  };
  "/admin/scenarios": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/providers": {
    params: {};
  };
  "/admin/audit": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/auth/login" | "/auth/logout" | "/dashboard" | "/game/new" | "/game/:id" | "/library" | "/library/:id" | "/api/auth/*" | "/admin" | "/admin/scenarios" | "/admin/users" | "/admin/providers" | "/admin/audit";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.logout.ts": {
    id: "routes/auth.logout";
    page: "/auth/logout";
  };
  "routes/_app/layout.tsx": {
    id: "routes/_app/layout";
    page: "/dashboard" | "/game/new" | "/game/:id" | "/library" | "/library/:id";
  };
  "routes/_app/dashboard.tsx": {
    id: "routes/_app/dashboard";
    page: "/dashboard";
  };
  "routes/_app/game.new.tsx": {
    id: "routes/_app/game.new";
    page: "/game/new";
  };
  "routes/_app/game.$id.tsx": {
    id: "routes/_app/game.$id";
    page: "/game/:id";
  };
  "routes/_app/library.tsx": {
    id: "routes/_app/library";
    page: "/library";
  };
  "routes/_app/library.$id.tsx": {
    id: "routes/_app/library.$id";
    page: "/library/:id";
  };
  "routes/api.auth.$.ts": {
    id: "routes/api.auth.$";
    page: "/api/auth/*";
  };
  "routes/admin/layout.tsx": {
    id: "routes/admin/layout";
    page: "/admin" | "/admin/scenarios" | "/admin/users" | "/admin/providers" | "/admin/audit";
  };
  "routes/admin/_index.tsx": {
    id: "routes/admin/_index";
    page: "/admin";
  };
  "routes/admin/scenarios.tsx": {
    id: "routes/admin/scenarios";
    page: "/admin/scenarios";
  };
  "routes/admin/users.tsx": {
    id: "routes/admin/users";
    page: "/admin/users";
  };
  "routes/admin/providers.tsx": {
    id: "routes/admin/providers";
    page: "/admin/providers";
  };
  "routes/admin/audit.tsx": {
    id: "routes/admin/audit";
    page: "/admin/audit";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.logout": typeof import("./app/routes/auth.logout.ts");
  "routes/_app/layout": typeof import("./app/routes/_app/layout.tsx");
  "routes/_app/dashboard": typeof import("./app/routes/_app/dashboard.tsx");
  "routes/_app/game.new": typeof import("./app/routes/_app/game.new.tsx");
  "routes/_app/game.$id": typeof import("./app/routes/_app/game.$id.tsx");
  "routes/_app/library": typeof import("./app/routes/_app/library.tsx");
  "routes/_app/library.$id": typeof import("./app/routes/_app/library.$id.tsx");
  "routes/api.auth.$": typeof import("./app/routes/api.auth.$.ts");
  "routes/admin/layout": typeof import("./app/routes/admin/layout.tsx");
  "routes/admin/_index": typeof import("./app/routes/admin/_index.tsx");
  "routes/admin/scenarios": typeof import("./app/routes/admin/scenarios.tsx");
  "routes/admin/users": typeof import("./app/routes/admin/users.tsx");
  "routes/admin/providers": typeof import("./app/routes/admin/providers.tsx");
  "routes/admin/audit": typeof import("./app/routes/admin/audit.tsx");
};