// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/game/new": {
    params: {};
  };
  "/game/:id": {
    params: {
      "id": string;
    };
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
  "/auth/login": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/providers": {
    params: {};
  };
  "/admin/prompts": {
    params: {};
  };
  "/admin/playground": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/game/new" | "/game/:id" | "/api/auth/*" | "/auth/login" | "/auth/logout" | "/admin" | "/admin/providers" | "/admin/prompts" | "/admin/playground";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/game.new.ts": {
    id: "routes/game.new";
    page: "/game/new";
  };
  "routes/game.$id.tsx": {
    id: "routes/game.$id";
    page: "/game/:id";
  };
  "routes/api.auth.$.ts": {
    id: "routes/api.auth.$";
    page: "/api/auth/*";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.logout.ts": {
    id: "routes/auth.logout";
    page: "/auth/logout";
  };
  "routes/admin/layout.tsx": {
    id: "routes/admin/layout";
    page: "/admin" | "/admin/providers" | "/admin/prompts" | "/admin/playground";
  };
  "routes/admin/_index.tsx": {
    id: "routes/admin/_index";
    page: "/admin";
  };
  "routes/admin/providers.tsx": {
    id: "routes/admin/providers";
    page: "/admin/providers";
  };
  "routes/admin/prompts.tsx": {
    id: "routes/admin/prompts";
    page: "/admin/prompts";
  };
  "routes/admin/playground.tsx": {
    id: "routes/admin/playground";
    page: "/admin/playground";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/game.new": typeof import("./app/routes/game.new.ts");
  "routes/game.$id": typeof import("./app/routes/game.$id.tsx");
  "routes/api.auth.$": typeof import("./app/routes/api.auth.$.ts");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.logout": typeof import("./app/routes/auth.logout.ts");
  "routes/admin/layout": typeof import("./app/routes/admin/layout.tsx");
  "routes/admin/_index": typeof import("./app/routes/admin/_index.tsx");
  "routes/admin/providers": typeof import("./app/routes/admin/providers.tsx");
  "routes/admin/prompts": typeof import("./app/routes/admin/prompts.tsx");
  "routes/admin/playground": typeof import("./app/routes/admin/playground.tsx");
};