/**
 * @file _index.tsx
 * @description Landing page route. Minimal route file delegating to HomePage component.
 * @module routes/_index
 *
 * @author Claude Code
 * @date 2025-01-26
 */

import type { MetaFunction } from "react-router";
import { HomePage } from "~/pages/HomePage";

// --- Meta ---

export const meta: MetaFunction = () => {
  return [
    { title: "JustPlay - AI Interactive Novel" },
    {
      name: "description",
      content: "Experience dynamic stories generated by AI.",
    },
  ];
};

// --- Component ---

export default function Index() {
  return <HomePage />;
}
