/**
 * @file _index.tsx
 * @description Landing page route. Public page introducing the game.
 * @module routes/_index
 */

import type { MetaFunction } from "react-router";
import { LandingPage } from "~/pages/LandingPage";

export const meta: MetaFunction = () => {
  return [
    { title: "JustPlay - AI Interactive Novel" },
    {
      name: "description",
      content:
        "Experience dynamic stories generated by AI. Choose your adventure.",
    },
  ];
};

export default function Index() {
  return <LandingPage />;
}
